### ISSUE TITLE
Everything is logged twice in development

### ISSUE THREAD

**Issue by zimbatm** [heroku/rails_stdout_logging#13] opened 2015-04-09 15:52 UTC
rails v4.1.6. In development mode, everything is logged twice in the console.

I think it hits the following issue: rails/rails#11415

**Comment by schneems** [comment] 2015-04-09 16:49
Duplicate of https://github.com/heroku/rails_stdout_logging/issues/1

**Closed by schneems** 2015-04-09 16:49 UTC
